[tool.poetry]
name = "burpeditor"
version = "0.1.0"
description = ""
authors = ["Natan Rodrigues <natanrce@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.3.3"

[tool.poetry.scripts]
"burpeditor" = "burpeditor.cli:cli"

[tool.poetry.group.dev.dependencies]
pytest = "^9.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
